/**
 * ...
 * @author 
 */
class RFGScoreManager extends RFGObjectManager{    

	 function RFGScoreManager(wnd, lay, owner) {
		super.RFGObjectManager(wnd, lay, owner);
		this.addObject(new RFGScore(this.window, this.parentLayer, this));
	}
    
	function consult(obj) {
		//相談を上位オブジェクトにたらいまわし
		return this.owner.consult(obj);
	}
    
    function finalize() {
		super.finalize();
    }
}

